### PR TITLE
Allow using reportlab for PDF generation instead of PyX+external programs

### PR DESCRIPTION
**Pull request by tuxlifan**
Since sometimes setting up LaTeX can be a challenge I decided to add support for reportlab as an alternative PDF "backend".

If the reportlab module can be loaded it will be preferred over the old PyX code path.
I tried to put the most common and important parts into functions so they can be used by either.

The qr-codes generated are exactly the same, as tested by "restoring" foo.asc from the example_output.pdf and backing it up again using the reportlab backend.

I added character samples and the "juicy" part of the restore script to the appendix to remove any doubts about correctly typing back the plaintext if needed and making it self-reliant (except for zbar, sort and sed) for power-users.

Switching to inch measurements and Letter paper format should work but is largely untested.

The chunking is faster now, using indexing instead of going by character.

PS: Thanks for doing all the research and heavy lifting! :)

### CODE REVIEW

**Comment by intra2net** [comment]
Sorry for not replying faster, I forgot that you have to explicitly "watch" your own repo to be notified of new pull requests in github.

Wow, what a big set of changes. Thanks for putting that kind of effort into the project.

When I wrote the initial version of paperbackup I did some research about the pdf generator to use. I saw reportlab, but it wasn't readily available for python 3 on all the distributions I checked. PyX and Latex had better availibility back then. I don't know if the situation has changed now. But isn't Latex easily available and packaged on all major distros for years now?

I'm just considering if it is really worth to support two pdf generators.

**Comment by tuxlifan** [comment]
> [One has] to explicitly "watch" [their] own repo to be notified of new pull requests in github.

Thanks for the tip!

> Thanks for putting that kind of effort into the project.

You're welcome, it was a textbook Scratch My Own Itch(tm) :)

> isn't Latex easily available and packaged on all major distros for years now?

I believe that is correct (for *major* distros). However, installing LaTeX does take several dozens or hundreds of MiB in my experience, plus the pyx code path relies on ghostscript and enscript on top of that.
I somehow couldn't get it to work when I tried back then without getting tons of (cryptic) error messages from pyx which I didn't manage to debug in a Reasonable Amount Of Time.
I just now tried again and this time pyx worked fine, so the above *is* a bit anecdotal...

> I'm just considering if it is really worth to support two pdf generators.

The major selling point I see for the `reportlab` version is that it is *very* easy to install *everything* needed for it into a python virtualenv and get to doing backups right away, even when being only a user without root access.
(ok, the qrencode might bite someone since IIRC it needs some libs to compile against and it would be nice to switch to a pure-python implementation like qrcode, which would need some serious tweaking though to produce exact matching qr codes - or I was too dumb when I tried it)

Even if you would decide against taking `reportlab` on board I would suggest for you to look at 034871aff078da532980fb1204d1636a8ab41009 since that gives a nice speed boost.

**Comment by intra2net** [comment]
I slept over this, talked to a colleague and we came to the conclusion that we just want to support one pdf backend. Adding a second one increases maintenance effort. 

We don't see enough benefit, as Latex and Pyx are readily available and easy to install. Yes, they need more than hundred megabytes, but I don't see a usecase for paperbackup on an embedded or other space constrained system. If Latex and Pyx don't work out of the box on your system, it is easy to install them in a VM, Docker container or similar.

Sorry, but I have to decline your pull request.

**Comment by tuxlifan** [comment]
Fair enough :)
I will probably then take out the pyx code from my fork-to-be and think of a new name (probably something unimaginative like `paperbackup-rptlab` or `paportbackup`) to avoid confusion.

**Comment by intra2net** [comment]
I don't know which libs and toolpaths will grow or die over the years. So maybe when I review the adoption of pdf toolkits in a few years, we might switch to an all-reportlab code. I just don't want the complexity of maintaining two optional pdf backends.

**Comment by tuxlifan** [comment]
I've switched the default branch of my repository to the `reportlab` branch and added a note in that README. This seems to be the path of least work for now and as you mentioned, who knows what will happen.
I'll just send another small PR for your README with a link in case someone would like to try the reportlab version.

**Pull request closed without merging**
